server.port=8081
spring.datasource.url=jdbc:oracle:thin:@//eklplmrageo.escortskubota.com:1525/NERPPDB.escortskubota.com
spring.datasource.username=SSO_ADMIN
spring.datasource.password=Sso12345
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.
sso.domain=https://idcs-5c4a0ebd0bcf497cbf9a834fd3cf38dd.identity.oraclecloud.com
sso.key=MmQ5ZTE4YTc0ZTM1NGViOThiY2Q0ZGNmMmY0NWMzODQ6aWRjc2NzLTNmMmM3MTgzLTM0OWQtNDlhMC1iYjliLWE0OWUyMGE3MWY1ZA==
report.base.path=/u01/AuditLogs
report.page.size=5000
