server.port=8081
spring.datasource.username=root
spring.datasource.password=Weldone@3210
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/idcs_sso
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#sso.domain=https://idcs-3d484bb1daf34d588eb3efd73f4917ea.identity.oraclecloud.com
#sso.key=NTkxOGVhMzZmNTY4NGNiMzk2MmFlZjE0MGNjYWFkMGU6aWRjc2NzLWFlZTE4YjQyLWRkYjQtNDc2ZC04OTRjLWMzZGQyNDUzMmU0Nw==
sso.domain=https://idcs-5c4a0ebd0bcf497cbf9a834fd3cf38dd.identity.oraclecloud.com
sso.key=MmQ5ZTE4YTc0ZTM1NGViOThiY2Q0ZGNmMmY0NWMzODQ6aWRjc2NzLTNmMmM3MTgzLTM0OWQtNDlhMC1iYjliLWE0OWUyMGE3MWY1ZA==